CREATE TABLE USERS
(
    USER_ID INT NOT NULL,
    USER_TYPE INT NOT NULL,
    EMAIL CHAR(128) NOT NULL,
    PASSWORD CHAR(32) NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY (USER_ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_USER_TYPES_FK FOREIGN KEY (USER_TYPE) REFERENCES USER_TYPES (TYPE_ID);

CREATE TABLE USER_TYPES
(
    TYPE_ID INT NOT NULL,
    TYPE_NAME CHAR(255) NOT NULL
);

ALTER TABLE USER_TYPES ADD CONSTRAINT USER_TYPES_PK PRIMARY KEY (TYPE_ID);

CREATE TABLE PRESENTATIONS
(
    PRESENTATION_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    PRESENTATION_TITLE CHAR(255) NOT NULL,
    PRESENTATION_DESCRIPTION char(255) NOT NULL,
    PRESENTATION_TIME CHAR(255) NOT NULL,
    PRESENTATION_PLACE CHAR(255) NOT NULL,
    PRESENTATION_DURATION CHAR(255) NOT NULL,
    PRESENTATION_MARK FLOAT NOT NULL
);

ALTER TABLE PRESENTATIONS ADD CONSTRAINT PRESENTATIONS_PK PRIMARY KEY (PRESENTATION_ID);
ALTER TABLE PRESENTATIONS ADD CONSTRAINT PRESENTATIONS_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE PRESENTATIONS ADD CONSTRAINT PRESENTATIONS_MARKS_FK FOREIGN KEY (PRESENTATION_MARK) REFERENCES MARKS (PRESENTATION_ID);
ALTER TABLE PRESENTATIONS ADD CONSTRAINT PRESENTATIONS_PARTICIPANTS_FK FOREIGN KEY (PRESENTATION_ID) REFERENCES PARTICIPANTS (PRESENTATION_ID);

CREATE TABLE MESSAGES
(
  MESSAGE_ID INT NOT NULL,
  USER_ID INT NOT NULL,
  PRESENTATION_ID INT NOT NULL,
  MESSAGE_TYPE INT NOT NULL,
  MESSAGE VARCHAR NOT NULL,
  IS_ANONYMOUS BOOLEAN NOT NULL
);

ALTER TABLE MESSAGES ADD CONSTRAINT MESSAGES_PK PRIMARY KEY (MESSAGE_ID);
ALTER TABLE MESSAGES ADD CONSTRAINT MESSAGES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE MESSAGES ADD CONSTRAINT MESSAGES_PRESENTATIONS_FK FOREIGN KEY (PRESENTATION_ID) REFERENCES PRESENTATIONS (PRESENTATION_ID);
ALTER TABLE MESSAGES ADD CONSTRAINT MESSAGES_MESSAGE_TYPES_FK FOREIGN KEY (MESSAGE_TYPE) REFERENCES MESSAGE_TYPES (TYPE_ID);

CREATE TABLE MESSAGE_TYPES
(
    TYPE_ID INT NOT NULL,
    TYPE_NAME CHAR(255) NOT NULL
);

ALTER TABLE MESSAGE_TYPES ADD CONSTRAINT MESSAGE_TYPES_PK PRIMARY KEY (TYPE_ID);

CREATE TABLE MARKS
(
    MARK_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    PRESENTATION_ID INT NOT NULL,
    MARK INT NOT NULL
);

ALTER TABLE MARKS ADD CONSTRAINT MARKS_PK PRIMARY KEY (MARK_ID);

CREATE TABLE PARTICIPANTS
(
    PARTICIPANT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    PRESENTATION_ID INT NOT NULL
);

ALTER TABLE PARTICIPANTS ADD CONSTRAINT PARTICIPANTS_PK PRIMARY KEY (PARTICIPANT_ID);